#!/bin/bash
# This file is used internally!!!! But you can use it outside of PC's server as it's useful!
sudo service docker start
sudo iptables -I FORWARD -d 192.168.0.0/16 -i docker0 -j REJECT --reject-with icmp-port-unreachable # Disable local network
while true; do
    node index.js &>> errorlogging.log
done